apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: cloudflare-test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-csi-cephfs
  resources:
    requests:
      storage: 10Gi
